version: "3.9"
services:
  web:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - back
  back:
    build: ./backend/
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "yarn prisma migrate deploy &&
      yarn prisma generate &&
      yarn prisma db seed &&
      node server.js"
    ports:
      - "4000:4000"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tubias
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
