version: "3.9"
services:
  web:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - back
  back:
    build: ./backend/
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
